//! The About window's third-party licences (ticket #64).
//!
//! The text is packaging/third-party-licences.txt, generated by
//! scripts/third-party-licences.sh and compiled in, so a release always
//! shows the licences of what it was built from.

use slint::{ModelRc, SharedString, VecModel};

const LICENCES: &str = include_str!("../../../packaging/third-party-licences.txt");

/// Lines longer than this are wrapped, so every list row is one line high.
const WIDTH: usize = 96;

/// The licences as list rows.
pub fn licence_lines() -> ModelRc<SharedString> {
    let mut rows = Vec::new();
    for line in LICENCES.lines() {
        wrap(line, &mut rows);
    }
    ModelRc::new(VecModel::from(rows))
}

/// Greedy word wrap that keeps a line's indentation on its continuation rows.
fn wrap(line: &str, rows: &mut Vec<SharedString>) {
    if line.chars().count() <= WIDTH {
        rows.push(line.into());
        return;
    }
    let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
    let mut row = indent.clone();
    for word in line.split_whitespace() {
        let row_len = row.chars().count();
        if row_len > indent.len() && row_len + 1 + word.chars().count() > WIDTH {
            rows.push(row.as_str().into());
            row = indent.clone();
        }
        if row.chars().count() > indent.len() {
            row.push(' ');
        }
        row.push_str(word);
    }
    rows.push(row.into());
}
